base_url = "https://Frankfurt-UAS-AI-Drone.github.io"
title = "Masterprojekt: Drohnen mit künstlicher Intelligenz"
description = "Team 'Bananastalker'"
build_search_index = true
compile_sass = true
taxonomies = [{ name = "tags" }]
theme = "apollo"

[markdown]
highlight_code = true

[extra]
theme = "toggle"                    
repo_url = "https://github.com/Frankfurt-UAS-AI-Drone/Frankfurt-UAS-AI-Drone.github.io"

menu = [
    { name = "Hardware", url = "/dronehardware"},
    { name = "Config", url = "/droneconfig"},
    { name = "Raspberry_Pi", url = "/raspberrypi"},
    { name = "App", url = "/application"},
    { name = "Further_Work", url = "/furtherwork"},
    { name = "About", url = "/about"},    
]

socials = [
    { name = "github", url = "https://github.com/Frankfurt-UAS-AI-Drone", icon = "github" },
]